### ISSUE TITLE
Dependency Injection failure : java.lang.NoSuchFieldException: mutex

### ISSUE THREAD

**Issue by chrisghost** [dwickern/sbt-classloader-leak-prevention#1]
Hello,
I am trying to use the plugin but it fails during dependency injection.

I tried it on my current project and on a new play-scala project (generated from activator).

I added the line in project/plugins.sbt and I get the following error : 
`Error injecting constructor, java.lang.NoSuchFieldException: mutex`

I am using Play 2.5.10

Also I could not find the `mutex` field you are referencing [here](https://github.com/dwickern/sbt-classloader-leak-prevention/blob/master/play-plugin/src/main/scala/com/github/dwickern/LeakPreventionModule.scala#L40) in the Play source code.

This plugin would be really useful for some of my coworkers, I would love to be able to make it run!

The full stacktrace:
```play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoSuchFieldException: mutex
  at com.github.dwickern.LeakPreventionHook.<init>(LeakPreventionModule.scala:22)
  at com.github.dwickern.LeakPreventionModule.bindings(LeakPreventionModule.scala:13):
Binding(class com.github.dwickern.LeakPreventionHook to self eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating com.github.dwickern.LeakPreventionHook

1 error]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:180)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:131)
        at scala.Option.map(Option.scala:146)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:131)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:129)
        at scala.util.Success.flatMap(Try.scala:231)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:129)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:121)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoSuchFieldException: mutex
  at com.github.dwickern.LeakPreventionHook.<init>(LeakPreventionModule.scala:22)
  at com.github.dwickern.LeakPreventionModule.bindings(LeakPreventionModule.scala:13):
Binding(class com.github.dwickern.LeakPreventionHook to self eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating com.github.dwickern.LeakPreventionHook

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:168)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:164)
Caused by: java.lang.NoSuchFieldException: mutex
        at java.lang.Class.getDeclaredField(Class.java:2070)
        at com.github.dwickern.LeakPreventionHook.addFinalStopHook(LeakPreventionModule.scala:40)
        at com.github.dwickern.LeakPreventionHook.<init>(LeakPreventionModule.scala:23)
        at com.github.dwickern.LeakPreventionHook$$FastClassByGuice$$551c1f23.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)```

**Comment by dwickern** [comment]
Thanks for trying this plugin!

It looks like `DefaultApplicationLifecycle` changed in 2.5.5:  https://github.com/playframework/playframework/commit/dba7b884114ca8472ce2efcb813680dda325ab3b#diff-bb4b362314b7269da03fc5356a5824f4

This should not be much trouble to fix. This unfortunate hack is necessary because there is no server shutdown hook accessible to the sbt plugin.

**Comment by dwickern** [comment]
The latest version supports Play 2.5.10. You will probably want to set `ClassLoaderLeakPreventor.threadWait := Duration.Zero`

**Comment by chrisghost** [comment]
Thank you for the fix ! @dwickern 

I now need to figure out how to make this work with AsyncHbase (threadpool got a little crazy on reload)

**Comment by dwickern** [comment]
Is it [this one](http://opentsdb.github.io/asynchbase/javadoc/index.html)? Make sure to call `shutdown` in a [lifecycle hook](https://www.playframework.com/documentation/2.5.x/ScalaDependencyInjection#stopping-cleaning-up). (you will need to convert from `com.stumbleupon.async.Deferred` to `scala.concurrent.Future`)
