### ISSUE TITLE
ClassLoader leak detected during manual sample test

### ISSUE THREAD

**Issue by Enalmada** [dwickern/sbt-classloader-leak-prevention#3]
If I go into sbt-plugin\src\sbt-test\play-plugin\play-2.5.12 and do sbt in interactive mode followed by "test", I usually get a ClassLoader leak detected error a few seconds after test runs.   This same problem is keeping me from running tests in my real project so I would love your advice on what to do to fix the sample because I think the same thing will apply.  Should this module be disabled somehow during test phase?  (I tried to do that but despite my best efforts I couldn't figure out how to disable it during "test").  Thanks for your help.

```
[play-2-5-12] $ test
[info] Initializing by loading some known offenders with leak safe classloader
[info] Initializing by loading some known offenders with leak safe classloader
[info] HomeControllerSpec:
[info] HomeController GET
[info] - should render the index page from a new instance of controller
[info] - should render the index page from the application
[info] - should render the index page from the router
[error] Internal registry of java.beans.PropertyEditorManager not found
[error] Internal registry of java.beans.PropertyEditorManager not found
[info] ScalaTest
[info] Run completed in 2 seconds, 711 milliseconds.
[info] Total number of tests run: 3
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[success] Total time: 3 s, completed Aug 4, 2017 5:29:32 PM
[play-2-5-12] $ [error] ClassLoader leak detected! To generate a heap dump, `set ClassLoaderLeakPreventor.enableLeakDetectionHeapDump := true`
[error] ClassLoader leak detected! To generate a heap dump, `set ClassLoaderLeakPreventor.enableLeakDetectionHeapDump := true`
```

**Comment by dwickern** [comment]
The check is merely informative, so it shouldn't break your build. You could disable the check with `ClassLoaderLeakPreventor.enableLeakDetection := false`.

This plugin does tend to detect leaks when running Play. It's possible that Play actually does leak, out of the box.

**Comment by Enalmada** [comment]
In my project, the default settings cause my test run to just hang on "ClassLoader leak detected!" and I have to CTRL-C to kill sbt to continue.

If I set enableLeakDetection := false, then the sample project does work fine.  Unfortunately my project still hangs so there must be something else going on.

```
[info] Default java.net.Authenticator not loaded by protected ClassLoader: org.apache.ivy.util.url.IvyAuthenticator@721f14c2
[error] Internal registry of java.beans.PropertyEditorManager not found
[warn] Waiting for Thread 'Thread[ScalaTest-dispatcher,5,main]' with Runnable of type org.scalatest.DispatchReporter$Propagator loaded by protected ClassLoader for 5000 ms. Thread stack trace:
[warn]  at sun.misc.Unsafe.park(Native Method)
[warn]  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[warn]  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[warn]  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
[warn]  at org.scalatest.LinkedBlockingQueue.take(JavaClassesWrappers.scala:43)
[warn]  at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:166)
[warn]  at java.lang.Thread.run(Thread.java:748)
Exception in thread "ScalaTest-dispatcher" java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at org.scalatest.LinkedBlockingQueue.take(JavaClassesWrappers.scala:43)
        at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:166)
        at java.lang.Thread.run(Thread.java:748)
[info] Thread 'Thread[ScalaTest-dispatcher,5,main]' with Runnable of type org.scalatest.DispatchReporter$Propagator loaded by protected ClassLoader no longer alive - no action needed.
```

Hacking at the code, it actually seems like adding "specs2 % Test" to libraryDependencies is causing the hang above.  Hmmmmmm......

**Comment by vegansk** [comment]
I also can't use the plugin together with specs2:
```
> ~core/testQuick
[info] Updating jsonApi
[info] Resolved jsonApi dependencies
[info] Updating xml
[info] Resolved xml dependencies
[info] Updating core
[info] Resolved core dependencies
[info] Initializing by loading some known offenders with leak safe classloader
[info] Initializing by loading some known offenders with leak safe classloader
[info] Initializing by loading some known offenders with leak safe classloader
[info] Default java.net.Authenticator not loaded by protected ClassLoader: sbt.ivyint.ErrorMessageAuthenticator@1a9ecf9
[error] Internal registry of java.beans.PropertyEditorManager not found
[warn] Waiting for Thread 'Thread[ScalaTest-dispatcher,5,main]' with Runnable of type org.scalatest.DispatchReporter$Propagator loaded by protected ClassLoader for 5000 ms. Thread stack trace: 
[warn]  at sun.misc.Unsafe.park(Native Method)
[warn]  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[warn]  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[warn]  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
[warn]  at org.scalatest.LinkedBlockingQueue.take(JavaClassesWrappers.scala:43)
[warn]  at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:166)
[warn]  at java.lang.Thread.run(Thread.java:748)
Exception in thread "ScalaTest-dispatcher" java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at org.scalatest.LinkedBlockingQueue.take(JavaClassesWrappers.scala:43)
        at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:166)
        at java.lang.Thread.run(Thread.java:748)
[info] Thread 'Thread[ScalaTest-dispatcher,5,main]' with Runnable of type org.scalatest.DispatchReporter$Propagator loaded by protected ClassLoader no longer alive - no action needed.
[info] Default java.net.Authenticator not loaded by protected ClassLoader: sbt.ivyint.ErrorMessageAuthenticator@1a9ecf9
[error] Internal registry of java.beans.PropertyEditorManager not found
[error] ClassLoader leak detected! To generate a heap dump, `set ClassLoaderLeakPreventor.enableLeakDetectionHeapDump := true`
[error] ClassLoader leak detected! To generate a heap dump, `set ClassLoaderLeakPreventor.enableLeakDetectionHeapDump := true`
```
